import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { button } from './page.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <button className={button['solid']} disabled>
          Disabled
        </button>
        <button className={button['solid']}>Solid</button>
        <button className={button['outline']}>Outline</button>
        <button className={button['ghost']}>Ghost</button>
        <button className={button['link']}>Link</button>
        {children}
      </body>
    </html>
  )
}
